name: Build & Deploy to Cloud Run

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Google Auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ vars.GCP_SERVICE_ACCOUNT }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - run: gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev

    - name: Build & Push Image
      run: |
        IMAGE="${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.ARTIFACT_REPO }}/pso"
        docker build -t $IMAGE:$GITHUB_SHA .
        docker push $IMAGE:$GITHUB_SHA

    - name: Deploy ke Cloud Run
      run: |
        IMAGE="${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.ARTIFACT_REPO }}/pso"
        gcloud run deploy my-app-service \
          --image=$IMAGE:$GITHUB_SHA \
          --platform=managed \
          --region=${{ secrets.GCP_REGION }} \
          --allow-unauthenticated \
          --port=8080 \
          --memory=512Mi \
          --set-env-vars="MONGODB_URI=${{ secrets.MONGODB_URI }}"